(deftheme cyberpunk
  "Created 2015-07-09.")

(custom-theme-set-variables
 'cyberpunk
 '(ansi-color-names-vector ["#000000" "#8b0000" "#00ff00" "#ffa500" "#7b68ee" "#dc8cc3" "#93e0e3" "#dcdccc"]))

(custom-theme-set-faces
 'cyberpunk
 '(button ((t (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#ffff00" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#d0bf8f" :underline t :weight normal))))
 '(bold ((((class color) (min-colors 89)) (:bold t))))
 '(bold-italic ((((class color) (min-colors 89)) (:bold t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#dcdccc"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#ffff00" :background "#2b2b2b" :box (:line-width -1 :style released-button)))))
 '(highlight ((((class color) (min-colors 89)) (:background "#333333"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#bfebbf" :underline t))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(match ((((class color) (min-colors 89)) (:background "#000000" :foreground "#ff1493"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#8b0000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ffff00"))))
 '(query-replace ((((class color) (min-colors 89)) (:background "#333333"))))
 '(italic ((((class color) (min-colors 89)) (nil))))
 '(tool-bar ((((class color) (min-colors 89)) (nil))))
 '(underline ((((class color) (min-colors 89)) (:underline nil))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#dcdccc" :background "#000000"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#61CE3C" :background "#000000"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#4c83ff" :background "#333333" :box (:line-width -1 :color "#4c83ff")))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#4D4D4D" :background "#1A1A1A" :box (:line-width -1 :color "#4c83ff")))))
 '(region ((((class color) (min-colors 89)) (:background "#7F073F"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ff0000"))))
 '(vertical-border ((t (:background "#000000" :foreground "#cccccc"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#FF6400"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#8B8989" :italic t))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#4c83ff"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ff1493"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#FBDE2D"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#919191"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#61CE3C"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#D8FA3C"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#D8FA3C"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff69b4"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#E9C062"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#ff0000"))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:background "#8B8989" :underline t))))
 '(ac-candidate-face ((((class color) (min-colors 89)) (:background "#999999" :foreground "#000000"))))
 '(ac-selection-face ((((class color) (min-colors 89)) (:background "#ff1493" :foreground "#000000"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#333333" :foreground "#ffffff"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#0A0A0A"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#333333"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:background "#000000" :foreground "#ff1493"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:foreground "#8b0000" :weight bold :underline t))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:foreground "#FBDE2D" :weight bold :underline t))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#ff1493" :background "#000000"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#ff1493" :background "#000000"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#999999" :backgroun "#000000"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#9fc59f" :background "#000000"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit default))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit outline-8 :height 1.0))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit outline-7 :height 1.0))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit outline-6 :height 1.0))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit outline-5 :height 1.0))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit outline-4 :height 1.0))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit outline-3 :height 1.0))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit outline-2 :height 1.0))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#9c6363" :background "#000000"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#d3d3d3" :background "#000000"))))
 '(fringe ((t (:background "black")))))

(provide-theme 'cyberpunk)
